# Generated by Django 6.0 on 2026-03-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.IntegerField(default=89388),
        ),
    ]
