# Generated by Django 6.0 on 2026-03-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.IntegerField(default=117450),
        ),
    ]
