# Generated by Django 6.0 on 2026-03-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.IntegerField(default=73622),
        ),
    ]
