# Generated by Django 6.0 on 2026-04-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.IntegerField(default=105426),
        ),
    ]
