# Generated by Django 6.0 on 2026-04-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_user_name_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.IntegerField(default=131452),
        ),
    ]
