# Generated by Django 6.0 on 2026-03-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cartitem_counter_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="bargain_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
