# Generated by Django 6.0 on 2026-03-25 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount_percentage",
        ),
    ]
