# Generated by Django 6.0 on 2026-03-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_discount_percentage_product_discount_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount_percentage",
        ),
    ]
